local cfg = {}
cfg.checkGroup = "title.enable"
cfg.titleColors = {
  ["basic"] = "^2",
  ["advanced"] = "^2",
  ["rare"] = "^3",
  ["unique"] = "^4",
  ["zombie"] = "^8",
  ["gold"] = "^3",
  ["supporter1"] = "^0",
  ["supporter2"] = "^0",
  ["supporter3"] = "^0",
  ["supporter4"] = "^0",
  ["supporter5"] = "^0",
  ["supporter6"] = "^0",
  ["supporter7"] = "^0^9",
  ["supporter8"] = "^0",
  ["supporter9"] = "^0",
  ["supporter10"] = "^0",
  ["god"] = "^0"
}
cfg.titles = {
  ["titlebox_basic1"] = {name = "💿 '굳건한'칭호", title = "💿굳건한", group = "title.basic1", div = "basic"},
  ["titlebox_basic2"] = {name = "💿 '든든한'칭호", title = "💿든든한", group = "title.basic2", div = "basic"},
  ["titlebox_basic3"] = {name = "💿 '따스한'칭호", title = "💿따스한", group = "title.basic3", div = "basic"},
  ["titlebox_basic4"] = {name = "💿 '아름다운'칭호", title = "💿아름다운", group = "title.basic4", div = "basic"},
  ["titlebox_basic5"] = {name = "💿 '향기로운'칭호", title = "💿향기로운", group = "title.basic5", div = "basic"},
  ["titlebox_basic6"] = {name = "💿 '깔끔한'칭호", title = "💿깔끔한", group = "title.basic6", div = "basic"},
  ["titlebox_basic7"] = {name = "💿 '더러운'칭호", title = "💿더러운", group = "title.basic7", div = "basic"},
  ["titlebox_basic8"] = {name = "💿 '웅장한'칭호", title = "💿웅장한", group = "title.basic8", div = "basic"},
  ["titlebox_basic9"] = {name = "💿 '거대한'칭호", title = "💿거대한", group = "title.basic9", div = "basic"},
  ["titlebox_basic10"] = {name = "💿 '날렵한'칭호", title = "💿날렵한", group = "title.basic10", div = "basic"},
  ["titlebox_basic11"] = {name = "💿 '의리하면'칭호", title = "💿의리하면", group = "title.basic11", div = "basic"},
  ["titlebox_basic12"] = {name = "💿 '잘생긴'칭호", title = "💿잘생긴", group = "title.basic12", div = "basic"},
  ["titlebox_advanced1"] = {name = "🍀 '거인'칭호", title = "🍀거인", group = "title.advanced1", div = "advanced"},
  ["titlebox_advanced2"] = {name = "🍀 '귀요미'칭호", title = "🍀귀요미", group = "title.advanced2", div = "advanced"},
  ["titlebox_advanced3"] = {name = "🍀 '현자'칭호", title = "🍀현자", group = "title.advanced3", div = "advanced"},
  ["titlebox_advanced4"] = {name = "🍀 '마법사'칭호", title = "🍀마법사", group = "title.advanced4", div = "advanced"},
  ["titlebox_advanced5"] = {name = "🍀 '전사'칭호", title = "🍀전사", group = "title.advanced5", div = "advanced"},
  ["titlebox_advanced6"] = {name = "🍀 '궁수'칭호", title = "🍀궁수", group = "title.advanced6", div = "advanced"},
  ["titlebox_advanced7"] = {name = "🍀 '도적'칭호", title = "🍀도적", group = "title.advanced7", div = "advanced"},
  ["titlebox_advanced8"] = {name = "🍀 '힐러'칭호", title = "🍀힐러", group = "title.advanced8", div = "advanced"},
  ["titlebox_advanced9"] = {name = "🍀 '보안관'칭호", title = "🍀보안관", group = "title.advanced9", div = "advanced"},
  ["titlebox_advanced10"] = {name = "🍀 'I'm'칭호", title = "🍀I'm", group = "title.advanced10", div = "advanced"},
  ["titlebox_rare1"] = {name = "🔆 '미인'칭호", title = "🔆미인", group = "title.rare1", div = "rare"},
  ["titlebox_rare2"] = {name = "🔆 '선녀'칭호", title = "🔆선녀", group = "title.rare2", div = "rare"},
  ["titlebox_rare3"] = {name = "🔆 '초절정'칭호", title = "🔆초절정", group = "title.rare3", div = "rare"},
  ["titlebox_rare4"] = {name = "🔆 '전설적인'칭호", title = "🔆전설적인", group = "title.rare4", div = "rare"},
  ["titlebox_rare5"] = {name = "🔆 '소문의주인공'칭호", title = "🔆소문의주인공", group = "title.rare5", div = "rare"},
  ["titlebox_rare6"] = {name = "🔆 '고인물''칭호", title = "🔆고인물", group = "title.rare6", div = "rare"},
  ["titlebox_unique1"] = {name = "💮 '진(眞)'칭호", title = "💮진(眞)", group = "title.unique1", div = "unique"},
  ["titlebox_unique2"] = {name = "💮 '용(龍)'칭호", title = "💮용(龍)", group = "title.unique2", div = "unique"},
  ["titlebox_unique3"] = {name = "💮 '화(花)'칭호", title = "💮화(花)", group = "title.unique3", div = "unique"},
  ["titlebox_unique4"] = {name = "💮 '신(神)'칭호", title = "💮신(神)", group = "title.unique4", div = "unique"},
  ["titlebox_god1"] = {name = "😎 '대장'칭호", title = "😎대장", group = "title.god1", div = "god"},
  ["titlebox_god2"] = {name = "🎇 '천사'칭호", title = "🎇천사", group = "title.god2", div = "god"},
  ["titlebox_god3"] = {name = "🎆 '악마'칭호", title = "🎆악마", group = "title.god3", div = "god"},
  ["titlebox_god4"] = {name = "🌞 '창조주'칭호", title = "🌞창조주", group = "title.god4", div = "god"},
  ["titlebox_zombie1"] = {name = "💀 'Hunter'칭호", title = "💀Hunter", group = "title.zombie1", div = "zombie"},
  ["titlebox_zombie2"] = {name = "💀 'Undead'칭호", title = "💀Undead", group = "title.zombie2", div = "zombie"},
  ["titlebox_zombie3"] = {name = "💀 'Pandemic'칭호", title = "💀Pandemic", group = "title.zombie3", div = "zombie"},
  ["titlebox_gold1"] = {name = "💰 '벼락부자'칭호", title = '💰벼락부자', group = "title.gold1", div = "gold"},
  ["titlebox_gold2"] = {name = "💰 '리치&리치'칭호", title = '💰Rich & Rich', group = "title.gold2", div = "gold"},
  ["titlebox_supporter1"] = {name = "🔥 '레드'칭호", title = "Red", group = "title.supporter1", div = "supporter1"},
  ["titlebox_supporter2"] = {name = "🔥 '에이스'칭호", title = "Ace", group = "title.supporter2", div = "supporter2"},
  ["titlebox_supporter3"] = {name = "🔥 '로얄'칭호", title = "Royal", group = "title.supporter3", div = "supporter3"},
  ["titlebox_supporter4"] = {name = "🔥 '노블레스'칭호", title = "Nobless", group = "title.supporter4", div = "supporter4"},
  ["titlebox_supporter5"] = {name = "🔥 '퍼스트'칭호", title = "First", group = "title.supporter5", div = "supporter5"},
  ["titlebox_supporter6"] = {name = "🔥 '퍼스트프라임'칭호", title = "FirstPrime", group = "title.supporter6", div = "supporter6"},
  ["titlebox_supporter7"] = {name = "🔥 '트리니티'칭호", title = "Trinity", group = "title.supporter7", div = "supporter7"},
  ["titlebox_supporter8"] = {name = "🔥 '크라운'칭호", title = "Crown", group = "title.supporter8", div = "supporter8"},
  ["titlebox_supporter9"] = {name = "🔥 '프레스티지'칭호", title = "Prestige", group = "title.supporter9", div = "supporter9"},
  ["titlebox_supporter10"] = {name = "🔥 '하이앤드'칭호", title = "Highend", group = "title.supporter10", div = "supporter10"}
}
return cfg
